### ISSUE TITLE
Rebuild image periodically

### ISSUE THREAD

**Issue by ineffyble** [rabblerouser/node-base-image#2]
This image was last built & pushed 3 months ago.

We probably want the image to be rebuilt periodically (to capture Node minor version upgrades, bug fixes, security fixes, from the upstream image).

This is hopefully something that can be set up in Docker Hub.

**Comment by camjackson** [comment]
That's a great point! Right now I don't think we have any image building set up to run in Docker hub. Instead we build the images as part of the pipelines in travis CI, and then push the images from travis into docker hub. I wonder if Travis supports periodic builds...

**Comment by camjackson** [comment]
Well that was easy! Just a few clicks in the travis CI web UI and we now have a weekly scheduled build! You can see [this build](https://travis-ci.org/rabblerouser/node-base-image/builds/338974588) was triggered as a 'cron' build.

Thanks for the suggestion 🙂
